server.port: 8001

spring:
  application:
    name: feign-consumer
  #指定zipkin服务端的url
  zipkin.base-url: http://localhost:9411
  #设定样本收集的比率为100%
  sleuth.sampler.percentage: 1.0

eureka.client.serviceUrl.defaultZone: http://localhost:1111/eureka

